FROM nvidia/cuda:10.1-devel-ubuntu18.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    build-essential \
    curl \
    cpio \
    libbz2-dev \
    libfftw3-dev \
    ccache \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

# CMake
RUN cd /usr/local \
&& curl -sL https://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.tar.gz | tar --strip-components=1 -xz \
&& rm -r /usr/local/man

# Intel Compiler
COPY intel-19.cfg /tmp/
RUN cd /tmp \
 && mkdir intel \
 && cd intel \
 && curl -sL http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/15809/parallel_studio_xe_2019_update5_cluster_edition_online.tgz | tar --strip-components=1 -xz \
 && USER=root ./install.sh --silent /tmp/intel-19.cfg \
 && cd \
 && rm -rf /tmp/intel /tmp/root/parallel_studio_xe_* \
 && rm -f /tmp/intelremotemonfifo.* /tmp/intel-19.cfg /tmp/intel.* /tmp/*.log

ENV CC=/opt/intel/bin/icc CXX=/opt/intel/bin/icpc PATH="/opt/intel/bin:${PATH}" LD_LIBRARY_PATH="/opt/intel/lib/intel64:${LD_LIBRARY_PATH}"
ENV I_MPI_ROOT=/opt/intel/compilers_and_libraries_2019.5.281/linux/mpi
ENV LD_LIBRARY_PATH="${I_MPI_ROOT}/intel64/lib:${LD_LIBRARY_PATH}" PATH="${I_MPI_ROOT}/intel64/bin:${PATH}"
RUN ln -s "${I_MPI_ROOT}/intel64/bin/mpicxx" "${I_MPI_ROOT}/intel64/bin/mpic++"

# Boost
RUN cd /tmp \
 && mkdir boost \
 && cd boost \
 && curl -sL https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2 | tar xj \
 && cd boost_1_66_0 \
 && echo 'using mpi : mpiicpc ;' > tools/build/src/user-config.jam \
 && ./bootstrap.sh \
 && ./b2 -j2 -d0 warnings=off toolset=intel install --prefix=/opt/boost \
 && cd \
 && rm -r /tmp/boost

ENV BOOST_ROOT=/opt/boost LD_LIBRARY_PATH="/opt/boost/lib:${LD_LIBRARY_PATH}"

RUN apt-get update && apt-get install -y \
    git \
    lcov \
    cython3 python3 python3-numpy python3-scipy \
    python3-setuptools \
    python3-vtk7 \
    libpython3-dev \
    vim \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN useradd -m espresso && usermod -a -G www-data espresso
USER 1000
WORKDIR /home/espresso
