FROM opensuse/leap:15.1
RUN ln -s /usr/sbin/update-alternatives /usr/bin
RUN zypper -n --gpg-auto-import-keys refresh \
&& zypper -n --gpg-auto-import-keys install \
  gcc-c++ \
  cmake \
  Modules \
  fftw3-devel \
  libboost_serialization1_66_0-devel libboost_mpi1_66_0-devel libboost_filesystem1_66_0-devel libboost_test1_66_0-devel \
  python3 \
  python3-Cython \
  python3-setuptools \
  python3-numpy \
  python3-numpy-devel \
  python3-scipy \
  python3-h5py \
  git \
  hdf5-openmpi-devel-static \
  libhdf5-103-openmpi2 \
  vim \
  which \
  ccache \
  curl
RUN /usr/sbin/useradd -m espresso
USER 1000
WORKDIR /home/espresso
