FROM opensuse/leap:15.0
MAINTAINER Florian Weik <fweik@icp.uni-stuttgart.de>
RUN zypper -n --gpg-auto-import-keys refresh \
&& zypper -n --gpg-auto-import-keys install \
  gcc-c++ \
  cmake \
  Modules \
  fftw3-devel \
  libboost_serialization1_66_0-devel libboost_mpi1_66_0-devel  libboost_filesystem1_66_0-devel libboost_test1_66_0-devel \
  python python-numpy python-numpy-devel python-h5py python-enum34 python-pylint \
  git \
  python-pycodestyle python-setuptools \
  python-Cython \
  python-devel \
#  hdf5-openmpi-devel libhdf5-101-openmpi \ # depends on OpenMPI 1.10, while Boost::MPI comes with OpenMPI 2.1
  vim \
  which \
  ccache \
  curl \
  && update-alternatives --install /usr/bin/pycodestyle pycodestyle /usr/bin/pycodestyle-2.7 1
RUN useradd -m espresso
USER 1000
WORKDIR /home/espresso
