FROM nvidia/cuda:9.0-devel-ubuntu16.04
MAINTAINER Florian Weik <fweik@icp.uni-stuttgart.de>
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    build-essential \
    clang-6.0 clang-tidy-6.0 clang-format-6.0 \
    curl \
    cython \
    openmpi-bin \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    python python-numpy python-h5py python-enum \
    git \
    pep8 pylint\
    python-numpydoc \
    python-pyvtk \
    python-pip \
    python-pyface \
    python-autopep8 python-pep8 \
    libpython-dev \
    libhdf5-openmpi-dev \
    doxygen \
    vim \
&& pip2 install requests \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* \
&& ln -s /usr/bin/llvm-symbolizer-6.0 /usr/bin/llvm-symbolizer \
&& ln -s /usr/bin/clang-format-6.0 /usr/bin/clang-format \
&& curl -Lo /usr/local/bin/git-clang-format https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/git-clang-format \
&& chmod +x /usr/local/bin/git-clang-format

RUN cd /tmp \
 && curl https://www.samba.org/ftp/ccache/ccache-3.4.3.tar.xz | tar xJ \
 && cd ccache-3.4.3 \
 && ./configure --prefix=/usr/local \
 && make && make install \
 && cd \
 && rm -r /tmp/ccache-3.4.3

RUN cd /usr/local \
&& curl -sL https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz | tar --strip-components=1 -xz \
&& rm -r /usr/local/man

RUN cd /usr/src && \
    git clone https://github.com/thrust/thrust.git && \
    rm -r /usr/local/cuda/include/thrust && \
    ln -s /usr/src/thrust/thrust /usr/local/cuda/include/thrust

ENV CC=/usr/bin/clang-6.0 CXX=/usr/bin/clang++-6.0 NVCC=/usr/bin/clang++-6.0

COPY boost.patch /tmp/
RUN cd /usr/include/boost && patch -p1 < /tmp/boost.patch

RUN useradd -m espresso && usermod -a -G www-data espresso
USER 1000
WORKDIR /home/espresso
