FROM nvidia/cuda:8.0-devel-ubuntu16.04
MAINTAINER Florian Weik <fweik@icp.uni-stuttgart.de>
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    build-essential \
    curl \
    cmake \
    openmpi-bin \
    lcov \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    python python-numpy python-h5py python-enum \
    git \
    pep8 pylint\
    python-vtk \
    python-pip \
    python-pyface \
    libpython-dev \
    libhdf5-openmpi-dev \
    doxygen \
    vim \
    ccache \
&& pip2 install --upgrade pip; pip2 install cython sphinx sphinxcontrib-bibtex numpydoc --upgrade \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

COPY thrust.patch /tmp/
RUN cd /usr/local/cuda/include/thrust && patch -p1 < /tmp/thrust.patch

RUN useradd -m espresso && usermod -a -G www-data espresso
USER 1000
WORKDIR /home/espresso
