FROM nvidia/cuda:9.0-devel-ubuntu16.04
MAINTAINER Jean-Noel Grad <jgrad@icp.uni-stuttgart.de>
ENV DEBIAN_FRONTEND noninteractive
### start of modified Dockerfile-9.0
RUN apt-get update && apt-get install -y \
    apt-utils \
    cmake \
    build-essential \
    curl \
    pkg-config \
    openmpi-bin libopenmpi-dev \
    lcov \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    libgsl-dev \
#   cython3 # use pip instead
    python3 python3-numpy python3-h5py \
    lcov \
    curl \
    git \
    pep8 pylint3 \
#   python3-vtk7 \ # not available in 16.04
    python3-sphinx python3-numpydoc python3-pip \
    libpython-dev \
    libhdf5-openmpi-dev \
    libhdf5-openmpi-10:amd64 \
    libhdf5-10:amd64 \
    doxygen \
    vim \
    ccache \
#&& pip3 install --upgrade sphinx sphinxcontrib-bibtex \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

### end of modified Dockerfile-9.0

# install Python3 packages required for testing tutorials and samples
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-dev python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && python3 -m pip install --upgrade pip \
    && pip3 install --upgrade setuptools \
    && pip3 install --upgrade six cython numpy scipy matplotlib ipython nbconvert sphinx sphinxcontrib-bibtex numpydoc

# install CMake 3.7.0
RUN cd /tmp \
 && mkdir cmake \
 && cd cmake \
 && curl -sL https://cmake.org/files/v3.7/cmake-3.7.0.tar.gz | tar --strip-components=1 -xz \
 && ./bootstrap \
 && make -j$(nproc) \
 && make install \
 && cd \
 && rm -rf /tmp/cmake

RUN useradd -m espresso && usermod -a -G www-data espresso
USER 1000
WORKDIR /home/espresso
