FROM nvidia/cuda:10.1-devel-ubuntu18.04
MAINTAINER Jean-Noel Grad <jgrad@icp.uni-stuttgart.de>
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    cmake \
    build-essential \
    pkg-config \
    openmpi-bin libopenmpi-dev \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    libgsl-dev \
    cython3 python3 python3-numpy python3-h5py \
    python3-dev python3-pip \
    lcov \
    git \
    pycodestyle pylint3 \
    python3-vtk7 \
    libhdf5-openmpi-dev \
    libhdf5-openmpi-100:amd64 \
    libhdf5-100:amd64 \
    doxygen \
    vim \
    ccache \
    graphviz \
    curl \
    wget \
    jq \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# install Python3 packages required for tutorials
RUN python3 -m pip install --upgrade pip \
    && pip3 install --upgrade setuptools \
    && pip3 install --upgrade six scipy matplotlib jupyter ipython nbconvert lxml 'sphinx!=2.1.0' sphinxcontrib-bibtex numpydoc

# install TeXlive 2019 from a PPA
RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common \
    && add-apt-repository -y ppa:jonathonf/texlive \
    && apt-get update \
    && apt-get install -y --no-install-recommends texlive-latex-recommended texlive-fonts-recommended \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m espresso && usermod -a -G www-data espresso
USER espresso

# install extra LaTeX packages locally
RUN tlmgr init-usertree \
    && tlmgr install pgf tikz-3dplot revtex units mhchem chemgreek todonotes upquote framed subfigure cleveref 2>&1 | tee $HOME/tlmgr.log \
    && if [ "$(grep 'TLPDB::from_file could not download' $HOME/tlmgr.log)" != "" ]; then exit 1; else rm $HOME/tlmgr.log; fi \
    && tlmgr install lm stmaryrd 2>&1 || : \
    && updmap -user

WORKDIR /home/espresso
