FROM ubuntu:focal
ENV DEBIAN_FRONTEND noninteractive
COPY build-and-install-scafacos.sh /tmp/
RUN apt-get update && apt-get install -y \
    apt-utils \
    cmake \
    ccache \
    autoconf \
    gfortran \
    build-essential \
    pkg-config \
    openmpi-bin \
    libopenmpi-dev \
    clang-9 \
    clang-tidy-9 \
    clang-format-9 \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    libgsl-dev \
    cython3 \
    python3 \
    python3-numpy \
    python3-scipy \
    python3-h5py \
    python3-vtk7 \
    python3-setuptools \
    libhdf5-openmpi-dev \
    libhdf5-openmpi-103:amd64 \
    libhdf5-103:amd64 \
    libblas-dev \
    liblapack-dev \
    vim \
    gdb \
    curl \
    lcov \
    git \
    jq \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*
RUN bash /tmp/build-and-install-scafacos.sh
RUN useradd -m espresso
USER 1000
WORKDIR /home/espresso
