FROM nvidia/cuda:9.0-devel-ubuntu16.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    build-essential \
    curl \
    lcov \
    pkg-config \
    openmpi-bin libopenmpi-dev \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    libgsl-dev \
    python3 python3-numpy python3-scipy python3-h5py python3-pip \
    git \
#   python3-vtk7 \ # not available in 16.04
    python3-lxml \
    python3-requests \
    python3-setuptools \
    libpython-dev \
    libhdf5-openmpi-dev \
    libhdf5-openmpi-10:amd64 \
    libhdf5-10:amd64 \
    libblas-dev \
    liblapack-dev \
    doxygen \
    vim \
    ccache \
    graphviz \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN useradd -m espresso && usermod -a -G www-data espresso
USER espresso
ENV HOME="/home/espresso"
# install Python3 packages locally
RUN pip3 install --user cython==0.26 cmake==3.10.3
ENV PATH="${PATH}:${HOME}/.local/bin"
WORKDIR /home/espresso
