FROM ubuntu:bionic
MAINTAINER Florian Weik <fweik@icp.uni-stuttgart.de>
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    cmake \
    build-essential \
    openmpi-bin \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    cython3 python3 python3-numpy python3-h5py \
    lcov \
    git \
    pycodestyle pylint3 \
    python3-vtk7 \
    libhdf5-openmpi-dev \
    libhdf5-openmpi-100:amd64 \
    libhdf5-100:amd64 \
    vim \
    ccache \
    curl \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN useradd -m espresso
USER 1000
WORKDIR /home/espresso

