FROM nvidia/cuda:9.0-devel-ubuntu16.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    cmake \
    build-essential \
    curl \
    lcov \
    pkg-config \
    openmpi-bin libopenmpi-dev \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    libgsl-dev \
    cython3 python3 python3-numpy python3-h5py \
    git \
#   python3-vtk7 \ # not available in 16.04
    libpython-dev \
    libhdf5-openmpi-dev \
    libhdf5-openmpi-10:amd64 \
    libhdf5-10:amd64 \
    doxygen \
    vim \
    ccache \
    graphviz \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN useradd -m espresso && usermod -a -G www-data espresso
USER 1000
WORKDIR /home/espresso
