FROM ubuntu:bionic
ENV DEBIAN_FRONTEND noninteractive
COPY build-and-install-scafacos.sh /tmp/
RUN apt-get update && apt-get install -y \
    apt-utils \
    cmake \
    build-essential \
    pkg-config \
    openmpi-bin libopenmpi-dev \
    gfortran \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    libgsl-dev \
    cython3 python3 python3-numpy python3-scipy python3-h5py \
    lcov \
    git \
    python3-vtk7 \
    libhdf5-openmpi-dev \
    libhdf5-openmpi-100:amd64 \
    libhdf5-100:amd64 \
    autoconf \
    vim \
    ccache \
    curl \
    jq \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*
RUN bash /tmp/build-and-install-scafacos.sh
RUN useradd -m espresso
USER 1000
WORKDIR /home/espresso
