FROM nvidia/cuda:9.0-devel-ubuntu16.04
MAINTAINER Florian Weik <fweik@icp.uni-stuttgart.de>
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    build-essential \
    curl \
    cpio \
    lcov \
    libbz2-dev \
    libfftw3-dev \
    cython python python-numpy python-enum \
    git \
    pep8 pylint\
    python-vtk \
    libpython-dev \
    doxygen \
    vim \
    ccache \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* \
&& rm /usr/lib/python2.7/dist-packages/vtk/vtkRenderingPython.so /usr/lib/python2.7/dist-packages/vtk/vtkVolumeRenderingPython.so /usr/lib/python2.7/dist-packages/vtk/vtkHybridPython.so /usr/lib/python2.7/dist-packages/vtk/vtkWidgetsPython.so /usr/lib/python2.7/dist-packages/vtk/vtkChartsPython.so /usr/lib/python2.7/dist-packages/vtk/vtkGeovisPython.so /usr/lib/python2.7/dist-packages/vtk/vtkInfovisPython.so /usr/lib/python2.7/dist-packages/vtk/vtkViewsPython.so /usr/lib/python2.7/dist-packages/vtk/vtkParallelPython.so

# CMake
RUN cd /usr/local \
&& curl -sL https://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.tar.gz | tar --strip-components=1 -xz

# Intel Compiler
COPY intel.cfg /tmp/
RUN cd /tmp \
 && mkdir intel \
 && cd intel \
 && curl -sL http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/11541/parallel_studio_xe_2017_update4_composer_edition.tgz | tar --strip-components=1 -xz \
 && USER=root ./install.sh --silent /tmp/intel.cfg \
 && cd \
 && rm -r /tmp/intel

ENV CC=/opt/intel/bin/icc CXX=/opt/intel/bin/icpc PATH="/opt/intel/bin:${PATH}" LD_LIBRARY_PATH="/opt/intel/lib/intel64:${LD_LIBRARY_PATH}"

# Intel MPI
COPY intel-mpi.cfg /tmp/
RUN cd /tmp \
 && mkdir intel-mpi \
 && cd intel-mpi \
 && curl -sL http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/12748/l_mpi_2018.2.199.tgz | tar --strip-components=1 -xz \
 && ./install.sh --silent /tmp/intel-mpi.cfg \
 && ln -s /opt/intel-mpi/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin/mpicxx /opt/intel-mpi/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin/mpic++ \
 && cd \
 && rm -r /tmp/intel-mpi

ENV PATH="/opt/intel-mpi/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin:${PATH}" I_MPI_ROOT=/opt/intel-mpi/compilers_and_libraries_2018.2.199/linux/mpi

# Boost
RUN cd /tmp \
 && mkdir boost \
 && cd boost \
 && curl -sL https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2 | tar xj \
 && cd boost_1_66_0 \
 && echo 'using mpi ;' > tools/build/src/user-config.jam \
 && ./bootstrap.sh \
 && ./b2 -j $(nproc) -d0 toolset=intel install --prefix=/opt/boost \
 && cd \
 && rm -r /tmp/boost

ENV BOOST_ROOT=/opt/boost LD_LIBRARY_PATH="/opt/boost/lib:${LD_LIBRARY_PATH}"

RUN useradd -m espresso && usermod -a -G www-data espresso
USER 1000
WORKDIR /home/espresso
