FROM rocm/dev-ubuntu-18.04:latest
MAINTAINER Florian Weik <fweik@icp.uni-stuttgart.de>
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    cmake \
    build-essential \
    pkg-config \
    openmpi-bin libopenmpi-dev \
    gfortran \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    libgsl-dev \
    cython3 python3 python3-numpy python3-h5py \
    lcov \
    git \
    pycodestyle pylint3 \
    python3-vtk7 \
    libhdf5-openmpi-dev \
    libhdf5-openmpi-100:amd64 \
    libhdf5-100:amd64 \
    autoconf \
    vim \
    ccache \
    rocrand rocfft rocthrust kmod \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

# fix rocprim namespace issue in rocthrust v2.7
# https://github.com/ROCmSoftwarePlatform/rocPRIM/pull/91
COPY rocm.patch /tmp/
RUN cd /opt/rocm && patch -p1 < /tmp/rocm.patch

RUN useradd -m espresso
USER 1000
WORKDIR /home/espresso

