FROM rocm/dev-ubuntu-18.04:latest
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    cmake \
    build-essential \
    pkg-config \
    openmpi-bin libopenmpi-dev \
    gfortran \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    libgsl-dev \
    cython3 python3 python3-numpy python3-h5py \
    lcov \
    git \
    pycodestyle pylint3 \
    python3-vtk7 \
    libhdf5-openmpi-dev \
    libhdf5-openmpi-100:amd64 \
    libhdf5-100:amd64 \
    autoconf \
    vim \
    ccache \
    rocrand rocfft rocthrust kmod \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

# patch rocFFT as a workaround for https://github.com/espressomd/espresso/issues/3235
RUN dpkg-query --show --showformat '${Version}' rocfft | grep -qv '0\.9\.7\.722' || ( \
    git clone -b rocm-2.9 https://github.com/ROCmSoftwarePlatform/rocFFT.git && \
    cd rocFFT && git diff 3b0813f~1..3b0813f library/src/plan.cpp | git apply && mkdir build && cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/opt/rocm -DCMAKE_CXX_COMPILER=/opt/rocm/bin/hcc -DCMAKE_CXX_FLAGS=--amdgpu-target=gfx900 && make -j$(nproc) install && \
    cd && rm -rf rocFFT )

RUN useradd -m espresso
USER 1000
WORKDIR /home/espresso

