FROM nvidia/cuda:11.0-devel-ubuntu20.04
ENV DEBIAN_FRONTEND noninteractive
COPY install-pfft.sh /tmp
COPY install-scafacos.sh /tmp
COPY ubuntu-packages.txt /tmp
RUN rm /etc/apt/sources.list.d/cuda.list \
    && apt-key del 7fa2af80 \
    && curl --silent -LO https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb \
    && dpkg -i cuda-keyring_1.0-1_all.deb \
    && rm cuda-keyring_1.0-1_all.deb
RUN apt-get update && xargs -a /tmp/ubuntu-packages.txt apt-get install --no-install-recommends -y \
    && apt-get install --no-install-recommends -y \
    libthrust-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN bash /tmp/install-pfft.sh     && rm /tmp/install-pfft.sh && \
    bash /tmp/install-scafacos.sh && rm /tmp/install-scafacos.sh && \
    ldconfig

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

RUN useradd -m espresso
USER espresso
ENV HOME="/home/espresso"
ENV PATH="${HOME}/.local/bin${PATH:+:$PATH}"
RUN pip3 install --no-cache --user scipy==1.6.0 cmake==3.17
WORKDIR /home/espresso
