FROM ubuntu:noble AS image_base
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
        apt-utils \
        build-essential \
        curl \
        ccache \
        cmake \
        cython3 \
        gcc-13 g++-13 \
        gdb \
        git \
        libboost-dev \
        libboost-filesystem-dev \
        libboost-mpi-dev \
        libboost-serialization-dev \
        libboost-test-dev \
        libopenmpi-dev \
        openssh-client \
        openmpi-bin \
        python3 \
        python3-dev \
        python3-h5py \
        python3-lxml \
        python3-numpy \
        python3-packaging \
        python3-pip \
        python3-scipy \
        python3-setuptools \
        python3-vtk9 \
        vim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

FROM image_base AS image_standalone
RUN useradd -m espresso
USER espresso
WORKDIR /home/espresso
