ARG BASE_VERSION=31
FROM fedora:${BASE_VERSION}
RUN yum -y install \
  blas-devel \
  boost-devel \
  boost-openmpi-devel \
  ccache \
  cmake \
  fftw-devel \
  gcc \
  gcc-c++ \
  gdb \
  git \
  hdf5-openmpi-devel \
  lapack-devel \
  make \
  openmpi-devel \
  python3 \
  python3-devel \
  python3-Cython \
  python3-numpy \
  python3-scipy \
  python3-pip \
  python3-setuptools \
  python3-h5py \
  vim \
  which \
  zlib-devel \
  && yum clean all
RUN useradd -m espresso
USER 1000
WORKDIR /home/espresso
