FROM nvidia/cuda:9.2-devel-ubuntu18.04
ENV DEBIAN_FRONTEND noninteractive
COPY ubuntu-packages.txt /tmp
RUN apt-get update && xargs -a /tmp/ubuntu-packages.txt apt-get install -y \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -m espresso && usermod -a -G www-data espresso
USER espresso
ENV HOME="/home/espresso"
WORKDIR /home/espresso
