FROM nvidia/cuda:10.1-devel-ubuntu18.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    build-essential \
    cmake ccache \
    gfortran \
    pkg-config \
    autoconf \
    openmpi-bin libopenmpi-dev \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    libgsl-dev \
    cython3 python3 python3-dev python3-pip python3-setuptools python3-six \
    python3-numpy python3-numpydoc python3-matplotlib python3-scipy \
    python3-h5py python3-vtk7 python3-lxml \
    ipython3 jupyter-notebook jupyter-nbconvert \
    libhdf5-openmpi-dev \
    libhdf5-openmpi-100:amd64 \
    libhdf5-100:amd64 \
    libblas-dev \
    liblapack-dev \
    curl wget \
    lcov \
    git \
    doxygen \
    vim \
    graphviz jq ffmpeg texlive-base \
&& apt-get install -y --no-install-recommends software-properties-common \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

# install ScaFaCoS
COPY build-and-install-scafacos.sh /tmp/
RUN bash /tmp/build-and-install-scafacos.sh \
&& rm /tmp/build-and-install-scafacos.sh

RUN useradd -m espresso && usermod -a -G www-data espresso
USER espresso

# install Python3 packages locally
RUN pip3 install --user --upgrade 'sphinx>=2.0,!=2.1.0' sphinxcontrib-bibtex 'MDAnalysis==0.16' 'pint>=0.9'
ENV PATH="/home/espresso/.local/bin:${PATH}"

WORKDIR /home/espresso
