FROM ubuntu:jammy
ENV DEBIAN_FRONTEND noninteractive
COPY install-pfft.sh /tmp
COPY install-pnfft.sh /tmp
COPY install-scafacos.sh /tmp
COPY ubuntu-packages.txt /tmp
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        cmake-format \
        clang-12 clang-tidy-12 clang-format-12 llvm-12 \
        doxygen \
        ffmpeg \
        gcc-10 g++-10 \
        graphviz \
        jupyter-notebook jupyter-nbconvert \
        libthrust-dev \
        nvidia-cuda-toolkit \
        pylint \
        python3-autopep8 \
        python3-matplotlib \
        python3-pint \
        python3-pycodestyle \
        python3-tqdm \
        texlive-base \
        $(cat /tmp/ubuntu-packages.txt) && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && rm /tmp/ubuntu-packages.txt

RUN bash /tmp/install-pfft.sh     && rm /tmp/install-pfft.sh && \
    bash /tmp/install-pnfft.sh    && rm /tmp/install-pnfft.sh && \
    bash /tmp/install-scafacos.sh && rm /tmp/install-scafacos.sh && \
    ldconfig

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

RUN useradd -m espresso
USER espresso
ENV HOME="/home/espresso"
ENV PATH="${HOME}/.local/bin${PATH:+:$PATH}"
RUN pip3 install --no-cache --user \
  pre-commit==2.15.0 \
  sphinx==4.5.0 \
  sphinx-toggleprompt==0.0.5 \
  sphinxcontrib-bibtex==2.4.2 \
  numpydoc==0.7.0
WORKDIR /home/espresso
