FROM nvidia/cuda:9.0-devel-ubuntu16.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    build-essential \
    clang-6.0 clang-tidy-6.0 clang-format-6.0 \
    curl \
    openmpi-bin \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    python3 python3-numpy python3-scipy python3-h5py \
    git \
#   python3-vtk7 \ # not available in 16.04
    python3-pip \
    python3-setuptools \
    libpython3-dev \
    libhdf5-openmpi-dev \
    libblas-dev \
    liblapack-dev \
    doxygen \
    vim \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* \
&& ln -s /usr/bin/llvm-symbolizer-6.0 /usr/bin/llvm-symbolizer \
&& ln -s /usr/bin/clang-format-6.0 /usr/bin/clang-format \
&& curl -Lo /usr/local/bin/git-clang-format https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/git-clang-format \
&& chmod +x /usr/local/bin/git-clang-format

RUN cd /tmp \
 && curl https://www.samba.org/ftp/ccache/ccache-3.4.3.tar.xz | tar xJ \
 && cd ccache-3.4.3 \
 && ./configure --prefix=/usr/local \
 && make && make install \
 && cd \
 && rm -r /tmp/ccache-3.4.3

RUN cd /usr/src && \
    git clone --depth=1 -b 1.9.5 https://github.com/thrust/thrust.git && \
    rm -r /usr/local/cuda/include/thrust && \
    ln -s /usr/src/thrust/thrust /usr/local/cuda/include/thrust

ENV CC=/usr/bin/clang-6.0 CXX=/usr/bin/clang++-6.0 NVCC=/usr/bin/clang++-6.0

# removes superfluous Clang-tidy warnings from the boost libraries
COPY boost.patch /tmp/
RUN cd /usr/include/boost && patch -p1 < /tmp/boost.patch

RUN useradd -m espresso && usermod -a -G www-data espresso
USER espresso
ENV HOME="/home/espresso"
# install Python3 packages locally
ENV PATH="${PATH}:${HOME}/.local/bin"
RUN pip3 install --upgrade pip
RUN pip install --user requests autopep8==1.3.4 pycodestyle==2.3.1 pylint==2.2.2 astroid==2.1.0 isort==4.3.4 cython==0.26 cmake==3.10.3 cmake-format==0.6.9 pre-commit
WORKDIR /home/espresso
