FROM nvidia/cuda:11.0-devel-ubuntu20.04
ENV DEBIAN_FRONTEND noninteractive
COPY build-and-install-scafacos.sh /tmp
COPY ubuntu-packages.txt /tmp
RUN apt-get update && xargs -a /tmp/ubuntu-packages.txt apt-get install --no-install-recommends -y \
    && apt-get install --no-install-recommends -y \
    libthrust-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN bash /tmp/build-and-install-scafacos.sh

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

RUN useradd -m espresso
USER espresso
ENV HOME="/home/espresso"
ENV PATH="${HOME}/.local/bin${PATH:+:$PATH}"
RUN pip3 install --user scipy==1.6.0
WORKDIR /home/espresso
