FROM fedora:40
RUN dnf -y install \
  blas-devel \
  boost-devel \
  boost-mpich-devel \
  ccache \
  cmake \
  environment-modules \
  fftw-devel \
  fftw-mpich-devel \
  gcc \
  gcc-c++ \
  gdb \
  git \
  hdf5-mpich-devel \
  lapack-devel \
  make \
  mpich-devel \
  python3 \
  python3-devel \
  python3-Cython \
  python3-lxml \
  python3-numpy \
  python3-scipy \
  python3-packaging \
  python3-pip \
  python3-setuptools \
  python3-h5py \
  vim \
  which \
  zlib-devel \
  && dnf clean all
RUN useradd -m espresso
USER 1000
WORKDIR /home/espresso
