FROM nvidia/cuda:10.1-devel-ubuntu18.04
ENV DEBIAN_FRONTEND noninteractive
COPY build-and-install-scafacos.sh /tmp/
COPY ubuntu-packages.txt /tmp
RUN apt-get update && xargs -a /tmp/ubuntu-packages.txt apt-get install -y \
    && apt-get install -y \
    doxygen \
    graphviz \
    ipython3 jupyter-notebook jupyter-nbconvert \
    python3-lxml python3-matplotlib \
    texlive-base \
    && apt-get install -y --no-install-recommends software-properties-common \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# install ScaFaCoS
RUN bash /tmp/build-and-install-scafacos.sh
RUN useradd -m espresso && usermod -a -G www-data espresso
USER espresso

# install Python3 packages locally
RUN pip3 install --user --upgrade 'sphinx>=2.0,!=2.1.0' sphinxcontrib-bibtex 'MDAnalysis==0.16' 'pint>=0.9'
ENV PATH="/home/espresso/.local/bin:${PATH}"

WORKDIR /home/espresso
