FROM debian:bookworm AS image_base
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        apt-utils \
        build-essential \
        cmake \
        ccache \
        curl \
        cython3 \
        gdb \
        git \
        libboost-dev \
        libboost-filesystem-dev \
        libboost-mpi-dev \
        libboost-serialization-dev \
        libboost-test-dev \
        libfftw3-dev \
        libhdf5-openmpi-dev \
        libpython3-dev \
        openmpi-bin \
        python3 \
        python3-h5py \
        python3-numpy \
        python3-packaging \
        python3-pip \
        python3-scipy \
        python3-setuptools \
        python3-vtk9 \
        vim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

FROM image_base AS image_standalone
RUN useradd -m espresso
USER espresso
WORKDIR /home/espresso
