FROM ubuntu:focal
ENV DEBIAN_FRONTEND noninteractive
COPY build-and-install-scafacos.sh /tmp
COPY ubuntu-packages.txt /tmp
RUN apt-get update && xargs -a /tmp/ubuntu-packages.txt apt-get install --no-install-recommends -y \
    && apt-get install --no-install-recommends -y \
    clang-9 clang-tidy-9 clang-format-9 llvm-9 \
    doxygen \
    ffmpeg \
    gcc-8 g++-8 \
    gcc-9 g++-9 \
    graphviz \
    ipython3 jupyter-notebook jupyter-nbconvert \
    libthrust-dev \
    nvidia-cuda-toolkit \
    python3-matplotlib \
    texlive-base \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN bash /tmp/build-and-install-scafacos.sh

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

RUN useradd -m espresso
USER espresso
ENV HOME="/home/espresso"
ENV PATH="${PATH}:${HOME}/.local/bin"
RUN pip3 install --user \
  autopep8==1.3.4 \
  pycodestyle==2.3.1 \
  pylint==2.2.2 \
  astroid==2.1.0 \
  isort==4.3.4 \
  cmake-format==0.6.9 \
  pre-commit \
  'sphinx>=2.0,!=2.1.0,!=3.0.0' \
  sphinxcontrib-bibtex \
  scipy==1.6.0 \
  'MDAnalysis>=0.18' \
  'pint>=0.9'
WORKDIR /home/espresso
