FROM ubuntu:jammy
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        apt-utils \
        build-essential \
        curl \
        ccache \
        cmake \
        cython3 \
        gcc-11 g++-11 \
        gdb \
        git \
        libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
        libopenmpi-dev \
        openssh-client \
        openmpi-bin \
        python3 \
        python3-dev \
        python3-h5py \
        python3-lxml \
        python3-numpy \
        python3-pip \
        python3-scipy \
        python3-setuptools \
        python3-vtk9 \
        vim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -m espresso
USER espresso
WORKDIR /home/espresso
