FROM rocm/dev-ubuntu-18.04:latest
ENV DEBIAN_FRONTEND noninteractive
#RUN sed -i 's|repo.radeon.com/rocm/apt/debian/|repo.radeon.com/rocm/apt/3.0/|' /etc/apt/sources.list.d/rocm.list \
&& apt-get update && apt-get install -y \
    apt-utils \
    cmake \
    build-essential \
    pkg-config \
    openmpi-bin libopenmpi-dev \
    gfortran \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    libgsl-dev \
    cython3 python3 python3-numpy python3-scipy python3-h5py \
    python3-setuptools \
    lcov \
    git \
    python3-vtk7 \
    libhdf5-openmpi-dev \
    libhdf5-openmpi-100:amd64 \
    libhdf5-100:amd64 \
    libblas-dev \
    liblapack-dev \
    autoconf \
    vim \
    ccache \
    rocrand rocfft rocthrust kmod \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN useradd -m espresso
USER 1000
WORKDIR /home/espresso

