FROM ubuntu:disco
ENV DEBIAN_FRONTEND noninteractive
COPY build-and-install-scafacos.sh /tmp/
COPY ubuntu-packages.txt /tmp
RUN apt-get update && xargs -a /tmp/ubuntu-packages.txt apt-get install -y \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN bash /tmp/build-and-install-scafacos.sh
RUN useradd -m espresso
USER 1000
WORKDIR /home/espresso
