FROM opensuse/leap:15.2
RUN ln -s /usr/sbin/update-alternatives /usr/bin
RUN zypper -n --gpg-auto-import-keys refresh \
&& zypper -n --gpg-auto-import-keys install \
  blas-devel \
  ccache \
  cmake \
  curl \
  fftw3-devel \
  gcc-c++ \
  gdb \
  git \
  hdf5-openmpi2-devel-static \
  lapack-devel \
  libboost_serialization1_66_0-devel libboost_mpi1_66_0-devel libboost_filesystem1_66_0-devel libboost_test1_66_0-devel \
  libhdf5-103-openmpi2 \
  Modules \
  openmpi2 \
  python3 \
  python3-Cython \
  python3-numpy \
  python3-numpy-devel \
  python3-scipy \
  python3-pip \
  python3-setuptools \
  python3-h5py \
  vim \
  which \
  zlib-devel-static
RUN /usr/sbin/useradd -m espresso
USER 1000
WORKDIR /home/espresso
