ARG BASE_VERSION=3.3
FROM rocm/dev-ubuntu-18.04:${BASE_VERSION}
ENV DEBIAN_FRONTEND noninteractive
COPY ubuntu-packages.txt /tmp
RUN apt-get update && xargs -a /tmp/ubuntu-packages.txt apt-get install --no-install-recommends -y \
    && apt-get install --no-install-recommends -y \
    rocrand rocfft rocthrust kmod \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m espresso
USER 1000
WORKDIR /home/espresso
