FROM debian:buster
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    cmake \
    build-essential \
    openmpi-bin \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    cython3 python3 python3-numpy python3-scipy python3-h5py python3-vtk7 \
    python3-setuptools \
    gdb \
    git \
    libpython3-dev \
    libhdf5-openmpi-dev \
    libblas-dev \
    liblapack-dev \
    python3-pip \
    vim \
    ccache \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN useradd -m espresso
USER 1000
WORKDIR /home/espresso
