FROM ubuntu:focal
ENV DEBIAN_FRONTEND noninteractive
COPY build-and-install-scafacos.sh /tmp/
COPY ubuntu-packages.txt /tmp
RUN apt-get update && xargs -a /tmp/ubuntu-packages.txt apt-get install -y \
    && apt-get install -y \
    clang-9 clang-tidy-9 clang-format-9 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN bash /tmp/build-and-install-scafacos.sh

RUN useradd -m espresso
USER espresso
ENV HOME="/home/espresso"
ENV PATH="${PATH}:${HOME}/.local/bin"
RUN pip3 install --user \
  autopep8==1.3.4 \
  pycodestyle==2.3.1 \
  pylint==2.2.2 \
  astroid==2.1.0 \
  isort==4.3.4 \
  cmake-format==0.6.9 \
  pre-commit
WORKDIR /home/espresso
