FROM ubuntu:bionic
ENV DEBIAN_FRONTEND noninteractive
COPY ubuntu-packages.txt /tmp
RUN apt-get update && xargs -a /tmp/ubuntu-packages.txt apt-get install -y \
    && apt-get install -y \
    libhdf5-openmpi-dev libhdf5-openmpi-100:amd64 libhdf5-100:amd64 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -m espresso
USER 1000
WORKDIR /home/espresso
