FROM debian:buster
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    build-essential \
    ccache \
    cmake \
    cython3 \
    gdb \
    git \
    libblas-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    libfftw3-dev \
    libhdf5-openmpi-dev \
    liblapack-dev \
    libpython3-dev \
    openmpi-bin \
    python3 \
    python3-numpy \
    python3-scipy \
    python3-h5py \
    python3-pip \
    python3-setuptools \
    python3-vtk7 \
    vim \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN useradd -m espresso
USER 1000
WORKDIR /home/espresso
