FROM nvidia/cuda:9.0-devel-ubuntu16.04
MAINTAINER Florian Weik <fweik@icp.uni-stuttgart.de>
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    cmake \
    build-essential \
    clang-6.0 clang-tidy-6.0 clang-format-6.0 \
    curl \
    openmpi-bin \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    cython3 python3 python3-numpy python3-h5py \
    git \
    pep8 pylint3 \
#   python3-vtk7 \ # not available in 16.04
    python3-pip \
    libpython3-dev \
    libhdf5-openmpi-dev \
    doxygen \
    vim \
&& pip3 install requests autopep8==0.9.1 \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* \
&& ln -s /usr/bin/llvm-symbolizer-6.0 /usr/bin/llvm-symbolizer \
&& ln -s /usr/bin/clang-format-6.0 /usr/bin/clang-format \
&& curl -Lo /usr/local/bin/git-clang-format https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/git-clang-format \
&& chmod +x /usr/local/bin/git-clang-format

RUN cd /tmp \
 && curl https://www.samba.org/ftp/ccache/ccache-3.4.3.tar.xz | tar xJ \
 && cd ccache-3.4.3 \
 && ./configure --prefix=/usr/local \
 && make && make install \
 && cd \
 && rm -r /tmp/ccache-3.4.3

RUN cd /usr/src && \
    git clone https://github.com/thrust/thrust.git && \
    rm -r /usr/local/cuda/include/thrust && \
    ln -s /usr/src/thrust/thrust /usr/local/cuda/include/thrust

ENV CC=/usr/bin/clang-6.0 CXX=/usr/bin/clang++-6.0 NVCC=/usr/bin/clang++-6.0

RUN useradd -m espresso && usermod -a -G www-data espresso
USER 1000
WORKDIR /home/espresso
