FROM fedora:latest
RUN yum -y install \
  gcc gcc-c++ make \
  cmake \
  openmpi-devel \
  fftw-devel \
  boost-devel boost-openmpi-devel \
  git \
  python3 \
  python3-devel \
  python3-Cython \
  python3-numpy \
  python3-h5py \
  hdf5-openmpi-devel \
  zlib-devel \
  which \
  vim \
  ccache \
  && yum clean all
RUN useradd -m espresso
USER 1000
WORKDIR /home/espresso
