FROM rocm/dev-ubuntu-16.04:latest
MAINTAINER Florian Weik <fweik@icp.uni-stuttgart.de>
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    cmake \
    build-essential \
    curl \
    pkg-config \
    openmpi-bin libopenmpi-dev \
    lcov \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    libgsl-dev \
    cython python python-numpy python-h5py python-enum \
    lcov \
    curl \
    git \
    pep8 pylint \
    python-vtk \
    python-pyface \
    libhdf5-openmpi-dev \
    libhdf5-openmpi-10:amd64 \
    libhdf5-10:amd64 \
    vim \
    ccache \
    rocfft \
    rocrand \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN cd /tmp \
 && curl -Ls https://github.com/ROCmSoftwarePlatform/Thrust/archive/6e31840.tar.gz | tar xz \
 && cp -r Thrust-6e31840ed4ac5e158e485c5cc22558a601a86ae8/thrust /opt/rocm/include/ \
 && rm -r Thrust-6e31840ed4ac5e158e485c5cc22558a601a86ae8

RUN apt-get remove -y rocfft \
 && cd /tmp \
 && git clone -b r2c https://github.com/mkuron/rocFFT.git \
 && cd rocFFT \
 && mkdir build && cd build \
 && CXX=/opt/rocm/bin/hcc cmake .. && make -j 4 install \
 && cd ../.. && rm -r rocFFT

RUN useradd -m espresso
USER espresso
WORKDIR /home/espresso

