FROM rocm/dev-ubuntu-16.04:latest
MAINTAINER Florian Weik <fweik@icp.uni-stuttgart.de>
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    apt-utils \
    cmake \
    build-essential \
    curl \
    pkg-config \
    openmpi-bin libopenmpi-dev \
    libfftw3-dev \
    libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev \
    libgsl-dev \
    cython python python-numpy python-h5py python-enum \
    lcov \
    git \
    pep8 pylint \
    python-vtk \
    python-pyface \
    libhdf5-openmpi-dev \
    libhdf5-openmpi-10:amd64 \
    libhdf5-10:amd64 \
    vim \
    ccache \
    rocrand rocfft hip-thrust \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN useradd -m espresso
USER espresso
WORKDIR /home/espresso

