FROM fedora:latest
MAINTAINER Florian Weik <fweik@icp.uni-stuttgart.de>
RUN yum -y install \
  gcc gcc-c++ make \
  cmake \
  openmpi-devel \
  fftw-devel \
  boost-devel boost-openmpi-devel \
  python numpy \
  git \
  python-pep8 \
  python2-Cython \
  pylint \
  python2-enum \
  python-devel \
  hdf5-openmpi-devel \
  zlib-devel \
  which \
  vim \
  ccache \
  && yum clean all
RUN useradd -m espresso
USER 1000
WORKDIR /home/espresso
