FROM centos/devtoolset-6-toolchain-centos7
USER root
MAINTAINER Florian Weik <fweik@icp.uni-stuttgart.de>
RUN yum -y install epel-release && yum -y install \
  make \
  cmake3 \
  openmpi-devel \
  fftw-devel \
  boost169-devel boost169-openmpi-devel \
  python numpy h5py\
  git \
  python-pep8 \
  python2-pip \
  python2-enum \
  python-devel \
  hdf5-openmpi-devel \
  zlib-devel \
  which \
  vim \
  ccache \
  && yum clean all \
  && ln -s /usr/bin/cmake3 /usr/bin/cmake \
  && pip2 install --upgrade pip; pip2 install cython pylint
ENV BOOST_ROOT=/usr/include/boost169
ENV BOOST_LIBRARYDIR=/usr/lib64/boost169
RUN ln -s /usr/lib64/openmpi/lib/boost169/libboost_mpi.so  /usr/lib64/boost169/libboost_mpi.so
RUN useradd -m espresso -u 1000
USER 1000
WORKDIR /home/espresso
